GROUP_LIGHT_SWITCHS = "gLightSwitch"
GROUP_WALL_SWITCH = "gWallSwitch"
GROUP_WALL_SWITCH_MOTION_SENSORS = "gWallSwitchMotionSensor"

SECURITY_ITEM_ARM_MODE = "PARTITION1_ARM_MODE"
SECURITY_STATE_ARM_AWAY = 1
